import type { PolicyPackRule, PolicyPacksResponse } from "../schemas";

const makePackRule = (id: string, control: string, title: string, summary: string, severity: string, category: string): PolicyPackRule => ({
  id,
  control,
  title,
  summary,
  rego_module: "policy/main.rego",
  rego_rule: "violations",
  category,
  severity,
  reference: "https://codegraph.io/standards",
  description: summary,
  alias_ids: [],
});

export const DEMO_POLICY_PACKS: PolicyPacksResponse = {
  status: "OK",
  packs: [
    {
      pack_id: "iso-27001",
      name: "ISO/IEC 27001 Benchmark Security Policy Pack",
      standard: "ISO-27001",
      version: "1.0.0",
      query_entrypoints: ["data.iso27001.violations"],
      enabled: true,
      description: "Default security and compliance rules for OWASP Benchmark controls.",
      rules_count: 10,
      rules: [
        makePackRule("ISO-A.10-WEAK-HASH", "Control A.10", "Weak Cryptographic Hash (MD5/SHA-1)", "Disallows MD5 and SHA-1 in security-sensitive password hashing and signature routines.", "high", "Cryptography"),
        makePackRule("ISO-A.10-WEAK-CRYPTO", "Control A.10", "Insecure Cryptographic Cipher (DES/ECB)", "Flags broken block ciphers and unauthenticated modes (DES, 3DES, Blowfish, ECB).", "high", "Cryptography"),
        makePackRule("ISO-A.10-WEAK-RANDOM", "Control A.10", "Insecure Random Number Generator", "Requires SecureRandom instead of java.util.Random for token and nonce generation.", "medium", "Cryptography"),
        makePackRule("ISO-A.8-SQL-INJECTION", "Control A.8", "Dynamic SQL Injection via Concatenation", "Detects unescaped request input interpolated into JDBC/ORM queries.", "high", "Injection"),
        makePackRule("ISO-A.8-PATH-TRAVERSAL", "Control A.8", "Arbitrary Path Traversal via Unvalidated Path", "Identifies file system calls with untrusted path arguments missing canonicalization.", "high", "File Operations"),
        makePackRule("ISO-A.8-CMD-INJECTION", "Control A.8", "Operating System Command Injection", "Flags ProcessBuilder / Runtime.exec calls with unsanitized command strings.", "high", "Command Execution"),
        makePackRule("ISO-A.8-LDAP-INJECTION", "Control A.8", "LDAP Search Filter Injection", "Prevents concatenation of user input into LDAP query expressions.", "high", "Directory Services"),
        makePackRule("ISO-A.8-XPATH-INJECTION", "Control A.8", "Dynamic XPath Query Injection", "Flags dynamically concatenated XPath expressions.", "high", "XML Processing"),
        makePackRule("ISO-A.9.4.1", "Control A.9.4.1", "Unrestricted Privileged Endpoint Execution", "Requires RBAC / authorization annotations on controller methods.", "high", "Access Control"),
        makePackRule("ISO-A.12.4.1", "Control A.12.4.1", "Missing Security Event Audit Logging", "Requires audit logging on critical state-changing service transactions.", "high", "Logging & Auditing"),
      ],
    },
    {
      pack_id: "pci-dss-4.0",
      name: "Payment Card Industry Data Security Standard (PCI-DSS) v4.0",
      standard: "PCI-DSS-4.0",
      version: "4.0.0",
      query_entrypoints: ["data.iso27001.violations"],
      enabled: true,
      description: "Compliance rules enforcing PCI-DSS v4.0 secure software development standards.",
      rules_count: 6,
      rules: [
        makePackRule("PCI-6.2.4.1-SQL-INJECTION", "Requirement 6.2.4.1", "SQL Injection in Cardholder Data Store", "Enforces parameterized queries to protect cardholder data repositories.", "critical", "Injection Flaws"),
        makePackRule("PCI-6.2.4.2-PATH-TRAVERSAL", "Requirement 6.2.4.2", "Path Traversal in Cardholder Statement Export", "Disallows unvalidated path traversal in file delivery routines.", "high", "Input Validation"),
        makePackRule("PCI-6.2.4.3-CMD-INJECTION", "Requirement 6.2.4.3", "Payment Batch OS Command Injection", "Blocks raw shell process invocation in batch payment pipelines.", "critical", "Execution Control"),
        makePackRule("PCI-3.4.1-WEAK-CRYPTO", "Requirement 3.4.1", "Insecure Cipher for Cardholder PAN Encryption", "Mandates AES-GCM or AES-CBC with HMAC for stored Primary Account Numbers (PAN).", "critical", "Protect Cardholder Data"),
        makePackRule("PCI-3.4.2-WEAK-HASH", "Requirement 3.4.2", "Insecure Cryptographic Hash for Verification", "Prohibits MD5/SHA-1 for payment verification tokens and message integrity.", "high", "Protect Cardholder Data"),
        makePackRule("PCI-8.3.1-WEAK-RANDOM", "Requirement 8.3.1", "Non-Cryptographic MFA Code Random Generator", "Requires cryptographically strong pseudorandom generation for one-time authentication codes.", "high", "Identity & Authentication"),
      ],
    },
    {
      pack_id: "owasp-top10-2021",
      name: "OWASP Top 10 Application Security Risks (2021)",
      standard: "OWASP-2021",
      version: "2021.1.0",
      query_entrypoints: ["data.iso27001.violations"],
      enabled: true,
      description: "Compliance rules aligned with the OWASP Top 10 (2021) standard categories.",
      rules_count: 8,
      rules: [
        makePackRule("A03:2021-SQL-INJECTION", "A03:2021-Injection", "A03:2021 SQL Injection Flaw", "Prevents dynamic SQL query construction without parameter binding.", "critical", "A03:2021-Injection"),
        makePackRule("A03:2021-CMD-INJECTION", "A03:2021-Injection", "A03:2021 OS Command Injection", "Blocks command execution constructed via string concatenation.", "critical", "A03:2021-Injection"),
        makePackRule("A03:2021-LDAP-INJECTION", "A03:2021-Injection", "A03:2021 LDAP Search Filter Injection", "Enforces LDAP filter escaping on directory queries.", "high", "A03:2021-Injection"),
        makePackRule("A03:2021-XPATH-INJECTION", "A03:2021-Injection", "A03:2021 Dynamic XPath Query Injection", "Requires parameterized XPath queries with variable resolvers.", "high", "A03:2021-Injection"),
        makePackRule("A01:2021-PATH-TRAVERSAL", "A01:2021-Broken Access Control", "A01:2021 Broken Access Control / Path Traversal", "Identifies file system access vulnerable to directory traversal.", "high", "A01:2021-Broken Access Control"),
        makePackRule("A02:2021-WEAK-CRYPTO", "A02:2021-Cryptographic Failures", "A02:2021 Deprecated Cryptographic Cipher (DES/ECB)", "Flags broken block ciphers and insecure ECB mode.", "critical", "A02:2021-Cryptographic Failures"),
        makePackRule("A02:2021-WEAK-HASH", "A02:2021-Cryptographic Failures", "A02:2021 Broken Cryptographic Hash (MD5)", "Disallows MD5 for password hashing and data integrity.", "high", "A02:2021-Cryptographic Failures"),
        makePackRule("A02:2021-WEAK-RANDOM", "A02:2021-Cryptographic Failures", "A02:2021 Predictable Pseudorandom Number Generator", "Requires SecureRandom for cryptographic key and token generation.", "high", "A02:2021-Cryptographic Failures"),
      ],
    },
    {
      pack_id: "nist-sp-800-53",
      name: "NIST SP 800-53 Rev 5 Security Controls",
      standard: "NIST-800-53",
      version: "5.1.0",
      query_entrypoints: ["data.iso27001.violations"],
      enabled: true,
      description: "Security and privacy controls for federal and enterprise information systems.",
      rules_count: 5,
      rules: [
        makePackRule("NIST-SI-10-SQL-INJECTION", "SI-10 Information Input Validation", "SI-10 SQL Input Validation and Sanitization", "Validates all database inputs against structured query rules.", "critical", "System & Information Integrity"),
        makePackRule("NIST-SI-10-CMD-INJECTION", "SI-10 Information Input Validation", "SI-10 Command Execution Input Validation", "Restricts process command execution parameters.", "critical", "System & Information Integrity"),
        makePackRule("NIST-SI-10-PATH-TRAVERSAL", "SI-10 Information Input Validation", "SI-10 File Path Input Sanitization", "Sanitizes file path parameters against directory traversal.", "high", "System & Information Integrity"),
        makePackRule("NIST-SC-13-CRYPTOGRAPHIC-PROTECTION", "SC-13 Cryptographic Protection", "SC-13 FIPS-Compliant Cryptographic Ciphers", "Enforces FIPS 140-3 approved cryptographic algorithms (AES-GCM, AES-CBC).", "critical", "System & Communications Protection"),
        makePackRule("NIST-SC-28-PROTECTION-AT-REST", "SC-28 Protection of Information at Rest", "SC-28 Strong Hashing for Information at Rest", "Requires SHA-256 or SHA-512 for data integrity and password storage.", "high", "System & Communications Protection"),
      ],
    },
  ],
};
