import type { Violation } from "../schemas";
import { makeFinding } from "./findingFactory";

export const DEMO_ISO_VIOLATIONS: Violation[] = [
  makeFinding({
    id: "ISO-A.10-WEAK-HASH",
    method: "com.acme.security.AuthService.hashPassword(String)",
    file: "/tmp/uploaded_code/app/src/main/java/com/acme/security/AuthService.java",
    line: 42,
    severity: "HIGH",
    standard: "ISO-27001",
    control: "Control A.10",
    cwes: ["CWE-328"],
    reason: "Cryptographically weak MD5 hashing used for credential storage.",
    code: `public String hashPassword(String password) throws Exception {\n    MessageDigest md = MessageDigest.getInstance("MD5");\n    byte[] digest = md.digest(password.getBytes(StandardCharsets.UTF_8));\n    return HexFormat.of().formatHex(digest);\n}`,
    callers: ["com.acme.controller.AuthController.register(UserRegistrationRequest)", "com.acme.controller.AuthController.login(LoginRequest)"],
    neighbors: ["com.acme.security.TokenService.verifyHash(String, String)"],
  }),
  makeFinding({
    id: "ISO-A.10-WEAK-CRYPTO",
    method: "com.acme.crypto.CipherUtil.encryptPayload(byte[], SecretKey)",
    file: "/tmp/uploaded_code/app/src/main/java/com/acme/crypto/CipherUtil.java",
    line: 78,
    severity: "HIGH",
    standard: "ISO-27001",
    control: "Control A.10",
    cwes: ["CWE-327"],
    reason: "Insecure DES/ECB cipher mode used without integrity authentication.",
    code: `public byte[] encryptPayload(byte[] data, SecretKey key) throws Exception {\n    Cipher cipher = Cipher.getInstance("DES/ECB/PKCS5Padding");\n    cipher.init(Cipher.ENCRYPT_MODE, key);\n    return cipher.doFinal(data);\n}`,
    callers: ["com.acme.service.PayloadEncryptionService.protectPayload(byte[])"],
    neighbors: ["com.acme.crypto.KeyManager.deriveKey()"],
  }),
  makeFinding({
    id: "ISO-A.10-WEAK-RANDOM",
    method: "com.acme.security.TokenService.generateSessionToken()",
    file: "/tmp/uploaded_code/app/src/main/java/com/acme/security/TokenService.java",
    line: 23,
    severity: "MEDIUM",
    standard: "ISO-27001",
    control: "Control A.10",
    cwes: ["CWE-330"],
    reason: "Predictable java.util.Random used to generate session tokens.",
    code: `public String generateSessionToken() {\n    Random rng = new Random();\n    byte[] tokenBytes = new byte[24];\n    rng.nextBytes(tokenBytes);\n    return Base64.getUrlEncoder().withoutPadding().encodeToString(tokenBytes);\n}`,
    callers: ["com.acme.security.SessionManager.createSession(User)"],
  }),
  makeFinding({
    id: "ISO-A.8-SQL-INJECTION",
    method: "com.acme.repository.AccountRepository.findByUsername(String)",
    file: "/tmp/uploaded_code/app/src/main/java/com/acme/repository/AccountRepository.java",
    line: 34,
    severity: "CRITICAL",
    standard: "ISO-27001",
    control: "Control A.8",
    cwes: ["CWE-89"],
    reason: "Dynamic SQL query constructed via raw string concatenation.",
    code: `public User findByUsername(String username) {\n    String sql = "SELECT * FROM accounts WHERE username = '" + username + "'";\n    return jdbcTemplate.queryForObject(sql, new UserRowMapper());\n}`,
    callers: ["com.acme.service.AccountService.getUserProfile(String)"],
    neighbors: ["com.acme.repository.AccountRepository.findAll()"],
  }),
  makeFinding({
    id: "ISO-A.8-PATH-TRAVERSAL",
    method: "com.acme.storage.FileStorageService.loadFile(String)",
    file: "/tmp/uploaded_code/app/src/main/java/com/acme/storage/FileStorageService.java",
    line: 19,
    severity: "HIGH",
    standard: "ISO-27001",
    control: "Control A.8",
    cwes: ["CWE-22"],
    reason: "Unvalidated filename passed to file system resolver without path normalization.",
    code: `public File loadFile(String filename) {\n    File baseDir = new File("/var/app/data");\n    return new File(baseDir, filename);\n}`,
    callers: ["com.acme.controller.DocumentController.download(String)"],
  }),
  makeFinding({
    id: "ISO-A.8-CMD-INJECTION",
    method: "com.acme.system.DiagnosticService.runPing(String)",
    file: "/tmp/uploaded_code/app/src/main/java/com/acme/system/DiagnosticService.java",
    line: 25,
    severity: "CRITICAL",
    standard: "ISO-27001",
    control: "Control A.8",
    cwes: ["CWE-78"],
    reason: "Untrusted host parameter concatenated into system command execution.",
    code: `public String runPing(String host) throws Exception {\n    Process p = Runtime.getRuntime().exec("ping -c 3 " + host);\n    return new String(p.getInputStream().readAllBytes());\n}`,
    callers: ["com.acme.controller.DiagnosticsController.ping(String)"],
  }),
  makeFinding({
    id: "ISO-A.9.4.1",
    method: "com.acme.controller.AdminController.deleteCustomer(String)",
    file: "/tmp/uploaded_code/app/src/main/java/com/acme/controller/AdminController.java",
    line: 52,
    severity: "HIGH",
    standard: "ISO-27001",
    control: "Control A.9.4.1",
    cwes: ["CWE-284"],
    reason: "Privileged administration endpoint exposed without role-based access authorization.",
    code: `@PostMapping("/api/v1/admin/customers/{id}/delete")\npublic ResponseEntity<Void> deleteCustomer(@PathVariable String id) {\n    customerService.purgeCustomerData(id);\n    return ResponseEntity.noContent().build();\n}`,
  }),
  makeFinding({
    id: "ISO-A.12.4.1",
    method: "com.acme.payment.PaymentService.charge(PaymentRequest)",
    file: "/tmp/uploaded_code/app/src/main/java/com/acme/payment/PaymentService.java",
    line: 61,
    severity: "HIGH",
    standard: "ISO-27001",
    control: "Control A.12.4.1",
    cwes: ["CWE-778"],
    reason: "Critical state-changing financial operation missing audit log event.",
    code: `public PaymentReceipt charge(PaymentRequest request) {\n    PaymentReceipt receipt = paymentGateway.execute(request);\n    return receipt;\n}`,
  }),
];
