import type { Violation } from "../schemas";
import { makeFinding } from "./findingFactory";

export const DEMO_OTHER_STANDARDS_VIOLATIONS: Violation[] = [
  // PCI-DSS 4.0
  makeFinding({
    id: "PCI-6.2.4.1-SQL-INJECTION",
    method: "com.acme.card.CardStore.queryCard(String)",
    file: "/tmp/uploaded_code/app/src/main/java/com/acme/card/CardStore.java",
    line: 29,
    severity: "CRITICAL",
    standard: "PCI-DSS-4.0",
    control: "Requirement 6.2.4.1",
    cwes: ["CWE-89"],
    reason: "PCI-DSS 4.0 Req 6.2.4.1: SQL injection in cardholder data repository.",
    code: `public CardRecord queryCard(String pan) {\n    String q = "SELECT * FROM cardholder_data WHERE pan = '" + pan + "'";\n    return db.queryForObject(q, CardRecord.class);\n}`,
    callers: ["com.acme.card.PaymentProcessor.process(CardRecord)"],
  }),
  makeFinding({
    id: "PCI-6.2.4.2-PATH-TRAVERSAL",
    method: "com.acme.card.StatementService.exportStatement(String)",
    file: "/tmp/uploaded_code/app/src/main/java/com/acme/card/StatementService.java",
    line: 38,
    severity: "HIGH",
    standard: "PCI-DSS-4.0",
    control: "Requirement 6.2.4.2",
    cwes: ["CWE-22"],
    reason: "PCI-DSS 4.0 Req 6.2.4.2: Path traversal in card statement file delivery.",
    code: `public File exportStatement(String accountId) {\n    File root = new File("/var/statements");\n    return new File(root, accountId + ".pdf");\n}`,
  }),
  makeFinding({
    id: "PCI-6.2.4.3-CMD-INJECTION",
    method: "com.acme.card.BatchSettlement.runBatch(String)",
    file: "/tmp/uploaded_code/app/src/main/java/com/acme/card/BatchSettlement.java",
    line: 45,
    severity: "CRITICAL",
    standard: "PCI-DSS-4.0",
    control: "Requirement 6.2.4.3",
    cwes: ["CWE-78"],
    reason: "PCI-DSS 4.0 Req 6.2.4.3: Command injection in settlement batch script.",
    code: `public void runBatch(String batchId) throws Exception {\n    new ProcessBuilder("sh", "-c", "/opt/settle.sh " + batchId).start();\n}`,
  }),
  makeFinding({
    id: "PCI-3.4.1-WEAK-CRYPTO",
    method: "com.acme.card.PanCipher.encryptPan(String)",
    file: "/tmp/uploaded_code/app/src/main/java/com/acme/card/PanCipher.java",
    line: 18,
    severity: "CRITICAL",
    standard: "PCI-DSS-4.0",
    control: "Requirement 3.4.1",
    cwes: ["CWE-327"],
    reason: "PCI-DSS 4.0 Req 3.4.1: Cardholder PAN encrypted using deprecated DES cipher.",
    code: `public byte[] encryptPan(String pan) throws Exception {\n    Cipher c = Cipher.getInstance("DES/CBC/PKCS5Padding");\n    c.init(Cipher.ENCRYPT_MODE, secretKey);\n    return c.doFinal(pan.getBytes());\n}`,
  }),
  makeFinding({
    id: "PCI-3.4.2-WEAK-HASH",
    method: "com.acme.card.PanHasher.hashPan(String)",
    file: "/tmp/uploaded_code/app/src/main/java/com/acme/card/PanHasher.java",
    line: 12,
    severity: "HIGH",
    standard: "PCI-DSS-4.0",
    control: "Requirement 3.4.2",
    cwes: ["CWE-328"],
    reason: "PCI-DSS 4.0 Req 3.4.2: Deprecated MD5 used for transaction integrity verification.",
    code: `public String hashPan(String pan) throws Exception {\n    MessageDigest md = MessageDigest.getInstance("MD5");\n    return HexFormat.of().formatHex(md.digest(pan.getBytes()));\n}`,
  }),
  makeFinding({
    id: "PCI-8.3.1-WEAK-RANDOM",
    method: "com.acme.card.MfaService.generateOtp()",
    file: "/tmp/uploaded_code/app/src/main/java/com/acme/card/MfaService.java",
    line: 15,
    severity: "HIGH",
    standard: "PCI-DSS-4.0",
    control: "Requirement 8.3.1",
    cwes: ["CWE-330"],
    reason: "PCI-DSS 4.0 Req 8.3.1: Non-cryptographic random generator used for MFA authentication code.",
    code: `public String generateOtp() {\n    Random r = new Random();\n    int otp = 100000 + r.nextInt(900000);\n    return String.valueOf(otp);\n}`,
  }),

  // OWASP Top 10
  makeFinding({
    id: "A03:2021-SQL-INJECTION",
    method: "com.acme.dao.UserDao.findUser(String)",
    file: "/tmp/uploaded_code/app/src/main/java/com/acme/dao/UserDao.java",
    line: 22,
    severity: "CRITICAL",
    standard: "OWASP-2021",
    control: "A03:2021-Injection",
    cwes: ["CWE-89"],
    reason: "OWASP A03:2021: SQL Injection via unescaped string parameter in statement.",
    code: `public User findUser(String id) throws SQLException {\n    Statement st = conn.createStatement();\n    ResultSet rs = st.executeQuery("SELECT * FROM users WHERE id = '" + id + "'");\n    return rs.next() ? new User(rs.getString(1)) : null;\n}`,
  }),
  makeFinding({
    id: "A03:2021-CMD-INJECTION",
    method: "com.acme.util.ShellRunner.execute(String)",
    file: "/tmp/uploaded_code/app/src/main/java/com/acme/util/ShellRunner.java",
    line: 14,
    severity: "CRITICAL",
    standard: "OWASP-2021",
    control: "A03:2021-Injection",
    cwes: ["CWE-78"],
    reason: "OWASP A03:2021: OS Command Injection via shell execution.",
    code: `public void execute(String script) throws IOException {\n    Runtime.getRuntime().exec("sh -c " + script);\n}`,
  }),
  makeFinding({
    id: "A03:2021-LDAP-INJECTION",
    method: "com.acme.directory.LdapAuthenticator.findUser(String)",
    file: "/tmp/uploaded_code/app/src/main/java/com/acme/directory/LdapAuthenticator.java",
    line: 28,
    severity: "HIGH",
    standard: "OWASP-2021",
    control: "A03:2021-Injection",
    cwes: ["CWE-90"],
    reason: "OWASP A03:2021: Unsanitized user string interpolated into LDAP search filter.",
    code: `public SearchResult findUser(String username) throws NamingException {\n    String filter = "(&(objectClass=user)(sAMAccountName=" + username + "))";\n    return dirContext.search("dc=acme,dc=com", filter, new SearchControls());\n}`,
  }),
  makeFinding({
    id: "A03:2021-XPATH-INJECTION",
    method: "com.acme.xml.XmlReportParser.extractUserNode(String)",
    file: "/tmp/uploaded_code/app/src/main/java/com/acme/xml/XmlReportParser.java",
    line: 20,
    severity: "HIGH",
    standard: "OWASP-2021",
    control: "A03:2021-Injection",
    cwes: ["CWE-643"],
    reason: "OWASP A03:2021: Dynamic XPath query concatenated with untrusted user input.",
    code: `public Node extractUserNode(String role) throws XPathExpressionException {\n    String query = "/users/user[@role='" + role + "']";\n    return (Node) xpath.evaluate(query, doc, XPathConstants.NODE);\n}`,
  }),
  makeFinding({
    id: "A01:2021-PATH-TRAVERSAL",
    method: "com.acme.avatar.AvatarService.loadAvatar(String)",
    file: "/tmp/uploaded_code/app/src/main/java/com/acme/avatar/AvatarService.java",
    line: 30,
    severity: "HIGH",
    standard: "OWASP-2021",
    control: "A01:2021-Broken Access Control",
    cwes: ["CWE-22"],
    reason: "OWASP A01:2021: Path traversal allows accessing files outside the avatar folder.",
    code: `public File loadAvatar(String name) {\n    return new File("/var/avatars/" + name);\n}`,
  }),

  // NIST SP 800-53
  makeFinding({
    id: "NIST-SI-10-SQL-INJECTION",
    method: "com.gov.tax.TaxRecordRepo.fetch(String)",
    file: "/tmp/uploaded_code/app/src/main/java/com/gov/tax/TaxRecordRepo.java",
    line: 35,
    severity: "CRITICAL",
    standard: "NIST-800-53",
    control: "SI-10 Information Input Validation",
    cwes: ["CWE-89"],
    reason: "NIST SP 800-53 Rev 5 SI-10: Database query lacking input sanitization.",
    code: `public TaxRecord fetch(String ssn) {\n    return db.query("SELECT * FROM records WHERE ssn = '" + ssn + "'");\n}`,
  }),
  makeFinding({
    id: "AU-2-EVENT-LOGGING",
    method: "com.acme.transfer.TransferAuditService.executeTransfer(TransferRequest)",
    file: "/tmp/uploaded_code/app/src/main/java/com/acme/transfer/TransferAuditService.java",
    line: 32,
    severity: "MEDIUM",
    standard: "NIST-800-53",
    control: "AU-2 Event Logging",
    cwes: ["CWE-778"],
    reason: "NIST SP 800-53 Rev 5 AU-2: Financial transfer transaction missing security event audit log.",
    code: `public TransferResult executeTransfer(TransferRequest req) {\n    accountService.debit(req.getFrom(), req.getAmount());\n    accountService.credit(req.getTo(), req.getAmount());\n    return TransferResult.success();\n}`,
  }),

  // Universal SAST (SARIF)
  makeFinding({
    id: "SEMGREP-CWE-79",
    method: "com.acme.controller.CommentController.renderComment(String)",
    file: "/tmp/uploaded_code/app/src/main/java/com/acme/controller/CommentController.java",
    line: 18,
    severity: "HIGH",
    standard: "SAST-SARIF",
    control: "CWE-79",
    cwes: ["CWE-79"],
    reason: "Universal SAST (Semgrep): Unescaped user comment written directly to HTTP response stream.",
    code: `@GetMapping("/comment")\npublic void renderComment(@RequestParam String comment, HttpServletResponse resp) throws IOException {\n    resp.getWriter().write("<div>" + comment + "</div>");\n}`,
    isSarif: true,
  }),
  makeFinding({
    id: "CODEQL-CWE-502",
    method: "com.acme.messaging.QueueConsumer.readPayload(byte[])",
    file: "/tmp/uploaded_code/app/src/main/java/com/acme/messaging/QueueConsumer.java",
    line: 24,
    severity: "CRITICAL",
    standard: "SAST-SARIF",
    control: "CWE-502",
    cwes: ["CWE-502"],
    reason: "Universal SAST (CodeQL): Insecure Java deserialization from untrusted message queue.",
    code: `public Object readPayload(byte[] bytes) throws Exception {\n    ObjectInputStream ois = new ObjectInputStream(new ByteArrayInputStream(bytes));\n    return ois.readObject();\n}`,
    isSarif: true,
  }),
  makeFinding({
    id: "SONAR-CWE-611",
    method: "com.acme.config.XmlConfigReader.loadXml(InputStream)",
    file: "/tmp/uploaded_code/app/src/main/java/com/acme/config/XmlConfigReader.java",
    line: 14,
    severity: "HIGH",
    standard: "SAST-SARIF",
    control: "CWE-611",
    cwes: ["CWE-611"],
    reason: "Universal SAST (SonarQube): XML External Entity (XXE) vulnerability in DocumentBuilderFactory.",
    code: `public Document loadXml(InputStream in) throws Exception {\n    DocumentBuilderFactory dbf = DocumentBuilderFactory.newInstance();\n    return dbf.newDocumentBuilder().parse(in);\n}`,
    isSarif: true,
  }),
  makeFinding({
    id: "SEMGREP-CWE-352",
    method: "com.acme.controller.ProfileUpdateController.updateEmail(String)",
    file: "/tmp/uploaded_code/app/src/main/java/com/acme/controller/ProfileUpdateController.java",
    line: 22,
    severity: "MEDIUM",
    standard: "SAST-SARIF",
    control: "CWE-352",
    cwes: ["CWE-352"],
    reason: "Universal SAST (Semgrep): State-changing POST endpoint missing CSRF token check.",
    code: `@PostMapping("/user/update-email")\npublic ResponseEntity<Void> updateEmail(@RequestParam String email) {\n    userProfileService.changeEmail(email);\n    return ResponseEntity.ok().build();\n}`,
    isSarif: true,
  }),
];
